version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'iuri'
      MYSQL_PASSWORD: '1234iuri'
      MYSQL_ROOT_PASSWORD: '1234iuri'
    ports:
      - '3308:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
